export const disasterIcons = {
  '1001': 'mdi:weather-tornado', // 台风
  '1003': 'bi:cloud-rain-fill', // 暴雨
  '1004': 'mingcute:snowstorm-line', // 暴雪
  '1005': 'streamline:wind-flow-2-solid', // 寒潮
  '1006': 'fluent:weather-squalls-24-filled', // 大风
  '1007': 'fluent:weather-duststorm-20-filled', // 沙尘暴
  '1008': 'fluent:weather-hail-night-24-filled', // 低温冻害
  '1009': 'ph:thermometer-hot-fill', // 高温
  '1011': 'typcn:weather-windy', // 干热风
  '1014': 'fluent:weather-thunderstorm-24-filled', // 雷电
  '1015': 'material-symbols:weather-hail', // 冰雹
  '1016': 'mdi:defrost', // 霜冻
  '1017': 'fluent:weather-fog-48-filled', // 大雾
  '1019': 'mingcute:haze-line', // 霾
  '1020': 'ion:thunderstorm', // 雷雨大风
  '1021': 'bi:pci-card-sound', // 道路结冰
  '1022': 'mingcute:dry-fill', // 干旱
  '1023': 'mdi:weather-windy', // 海上大风
  '1024': 'fa6-solid:hot-tub-person', // 高温中暑
  '1025': 'mdi:pine-tree-fire', // 森林火险
  '1027': 'mingcute:hail-fill', // 冰冻
  '1029': 'mdi:garbage-can-empty', // 重污染
  '1030': 'material-symbols:weather-mix', // 低温雨雪冰冻
  '1031': 'streamline:wind-flow-1-solid', // 强对流
  '1033': 'material-symbols:weather-snowy', // 大雪
  '1034': 'material-symbols:severe-cold-rounded', // 寒冷
  '1037': 'game-icons:ground-sprout', // 地质灾害气象风险
  '1039': 'mdi:hot-cold', // 强降温
  '1041': 'mingcute:fire-fill', // 森林（草原）火险
  '1042': 'fa6-solid:kit-medical', // 医疗气象
  '1048': 'mdi:hot-cold', // 降温
  '1051': 'mdi:weather-dust', // 沙尘
  '1052': 'bi:cloud-lightning-rain-fill', // 海上雷雨大风
  '1053': 'mingcute:fog-fill', // 海上大雾
  '1056': 'healthicons:cold-chain', // 低温
  '1057': 'fluent:weather-rain-snow-48-filled', // 道路冰雪
  '1058': 'ic:round-thunderstorm', // 雷暴大风
  '1059': 'ph:thermometer-cold-fill', // 持续低温
  '1062': 'typcn:weather-windy-cloudy', // 海区大风
  '1065': 'fluent:weather-haze-24-filled', // 海区大雾
  '1069': 'uis:coronavirus', // 感冒等呼吸道疾病气象条件
  '1072': 'ion:fitness', // 心脑血管疾病气象条件
  '1081': 'material-symbols:rainy-snow', // 电线积冰
  '1082': 'healthicons:cardiogram', // 脑卒中气象风险
  '11B03': 'bi:cloud-rain-fill', // 暴雨
  '11B04': 'mingcute:snowstorm-line', // 暴雪
  '11B05': 'streamline:wind-flow-2-solid', // 寒潮
  '11B06': 'fluent:weather-squalls-24-filled', // 大风
  '11B14': 'fluent:weather-thunderstorm-24-filled', // 雷电
  '11B17': 'fluent:weather-fog-48-filled', // 大雾
  '11B19': 'mingcute:haze-line', // 霾
  '11B21': 'bi:pci-card-sound', // 道路结冰
  '11B23': 'mdi:weather-windy', // 海上大风
  '11B33': 'material-symbols:weather-snowy', // 大雪
  '11B34': 'material-symbols:severe-cold-rounded', // 寒冷
  '11B39': 'mdi:hot-cold', // 强降温
  '11B57': 'fluent:weather-rain-snow-48-filled', // 道路冰雪
  '11B99': 'ion:notifications', // 其他
  '1201': 'ic:round-water', // 洪水
  '1209': 'fa6-solid:bridge-water', // 中小河流洪水和山洪气象风险
  '1211': 'icon-park-solid:water', // 中小河流洪水气象风险
  '1214': 'ic:round-flood', // 山洪灾害事件
  '1219': 'fa6-solid:house-flood-water', // 山洪灾害气象风险
  '1248': 'game-icons:ground-sprout', // 地质灾害气象风险
  '9999': 'ion:notifications', // 其他
};
